accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('register/',views.registerPage,name="register"),
    path('shopregister/',views.shopOwnerRegisterPage,name="shopregister"),
    path('token/',views.token_send,name="token_send"),
    path('success/',views.success,name="success"),
    path('verify/<auth_token>',views.verify,name="verify"),
    path('error/',views.error_page,name='error'),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('user/dashboard/',views.userPage,name='user-page'),
    path('account/',views.viewAccount,name='account'),
    path('account/edit/',views.accountSettings,name='edit_account'),
    path('change-password/',views.change_password,name = 'change_password'),
    path('', views.home,name='home'),
    path('products/', views.products,name='products'),
    path('flash_sell/', views.flashSell,name='flash'),
    path('products/setting/<str:pk>/', views.productSetting, name='product_setting'),
    path('customer/<str:pk>/', views.customers,name='customer'),
    path('update_order/<str:pk>/',views.updateOrder,name='update_order'),
    path('update_stock/<str:pk>/',views.updateStock,name='update_stock'),
    path('delete_order/<str:pk>/',views.deleteOrder,name='delete_order'),
    path('mail/',views.mail_letter,name='mail'),
    path('create/tag/',views.createTag,name='tag'),
    path('create/category/',views.createCategory,name='category'),
    path('reset-password/', PasswordResetView.as_view(
        template_name= 'accounts/reset_password.html',
        success_url=reverse_lazy('password_reset_done'),
        email_template_name= 'accounts/reset_password_email.html'
    ), name='reset_password'),

    path('reset-password/done/',PasswordResetDoneView.as_view(
        template_name= 'accounts/reset_password_done.html'
    ),name= 'password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(
        template_name= 'accounts/reset_password_confirm.html',
         success_url=reverse_lazy('password_reset_complete'),
    ),name= 'password_reset_confirm' ),
    path('reset-password/complete/',PasswordResetCompleteView.as_view(
        template_name= 'accounts/reset_password_complete.html'
    ),name ='password_reset_complete')
]

online_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('ecommerce_web.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    phone = models.CharField(max_length=200, null=True )
    profile_pic = models.ImageField(default="profile.png",null = True,blank = True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username

class ShopOwner(models.Model):
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    phone = models.CharField(max_length=200, null=True )
    profile_pic = models.ImageField(default="profile.png",null = True,blank = True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user = instance)
        print('Profile created')


def update_profile(sender, instance, created, **kwargs):
    if created == False:
        instance.UserProfile.save()
        print('Profile Updated')


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    shopowner = models.ForeignKey(ShopOwner, null=True, on_delete= models.SET_NULL)
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.ManyToManyField(Category)
    description = models.CharField(max_length=200, null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)
    digital = models.BooleanField(default=False, null=True, blank=False)
    img = models.ImageField(default="product-pic.jpg",null = True,blank = True)
    stock = models.IntegerField(default=0, null = True,blank = True)
    discount = models.IntegerField(default=0, null = True,blank = True)
    discount_amount = models.FloatField(default=0, null = True,blank = True)
    rate = models.FloatField(default=0, null = True,blank = True)

    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete= models.SET_NULL)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    

accounts/views.py
from django.shortcuts import render,redirect
from django.forms import inlineformset_factory
from django.contrib.auth.models import User
import uuid
from django.conf import settings
from django.core.mail import send_mail
from django_pandas.io import read_frame
from .models import *
from ecommerce_web.models import *
from .forms import *
from ecommerce_web.forms import *
from django.contrib.auth import authenticate,login,logout
from .filters import OrderFilter
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .decorators import unauthenticted_user, allowed_users,shopowner_only
from django.contrib.auth.forms import PasswordChangeForm

# Create your views here.

@unauthenticted_user
def registerPage(request):
    form = CreateUserForm()
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password1')
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        try:
            if User.objects.filter(username=username).first():
                messages.success(request, 'Username is taken.')
                return redirect('/register')

            elif User.objects.filter(email=email).first():
                messages.success(request, 'This Email is taken.')
                return redirect('/register')

            if form.is_valid():
                user_obj = User.objects.create(username =username,email=email)
                user_obj.set_password(password)
                user_obj.save()
                auth_token=str(uuid.uuid4())
                profile_obj = UserProfile.objects.create(user = user_obj,auth_token=auth_token)
                profile_obj.save()
                group = Group.objects.get(name = 'customer')
                user_obj.groups.add(group)
                Customer.objects.create(
                    user = user_obj
                )
                send_mail_after_registration(email,auth_token)
                messages.success(request,'Account was created for ' + username)
                return redirect('/token')
        
        except Exception as e:
            print(e)

    context = {'form':form}
    return render(request,'accounts/register.html',context)

@unauthenticted_user
def shopOwnerRegisterPage(request):
    form = CreateUserForm()
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password1')
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        try:
            if User.objects.filter(username=username).first():
                messages.success(request, 'Username is taken.')
                return redirect('/shopregister')

            elif User.objects.filter(email=email).first():
                messages.success(request, 'This Email is taken.')
                return redirect('/shopregister')

            if form.is_valid():
                user_obj = User.objects.create(username =username,email=email,is_staff = True)
                user_obj.set_password(password)
                user_obj.save()
                auth_token=str(uuid.uuid4())
                profile_obj = UserProfile.objects.create(user = user_obj,auth_token=auth_token)
                profile_obj.save()
                group = Group.objects.get(name = 'shopowner')
                user_obj.groups.add(group)
                ShopOwner.objects.create(
                    user = user_obj
                )
                send_mail_after_registration(email,auth_token)
                messages.success(request,'Account was created for ' + username)
                return redirect('/token')
        
        except Exception as e:
            print(e)

    context = {'form':form}
    return render(request,'accounts/shopregister.html',context)

def success(request):
    return render(request, 'accounts/success.html')

def token_send(request):
    return render(request, 'accounts/token_send.html')

def send_mail_after_registration(email,token):
    subject = 'Account activation for Online Store'
    message = f'Hello there! Click this link to verify your account http://127.0.0.1:8000/verify/{token}'
    email_form = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject,message,email_form,recipient_list)

def verify(request,auth_token):
    try:
        profile_obj = UserProfile.objects.filter(auth_token = auth_token).first()
        if profile_obj:
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request,'Your account has been verified')
            return redirect('/login')
        else:
            return redirect('/error')
    
    except Exception as e:
        print(e)

def error_page(request):
    return render(request,'accounts/error.html')

@unauthenticted_user
def loginPage(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username, password=password)

        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.info(request,'Username or Password is incorrect')
    context = {}
    return render(request,'accounts/login.html',context)

def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
@shopowner_only
def home(request):
    shopowner = request.user.shopowner
    orders = OrderItem.objects.filter(shop=shopowner).order_by('-date_added')
    customers = Customer.objects.all()

    total_customers = customers.count()
    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending = orders.filter(status='Pending').count()

    context = {'orders':orders,'customers':customers,
    'total_customers':total_customers,'total_orders':total_orders,
    'delivered':delivered,'pending':pending
    }

    return render(request,'accounts/dashboard.html', context)

@login_required(login_url='login')
def userPage(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}

    orders = request.user.customer.orderitem_set.all().order_by('-date_added')

    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending = orders.filter(status='Pending').count()

    myFilter = OrderFilter(request.GET,queryset=orders)
    orders = myFilter.qs

    context = {'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'orders':orders,'total_orders':total_orders,'cartItems':cartItems,
    'delivered':delivered,'pending':pending,'myFilter':myFilter}
    return render(request, 'accounts/user.html', context)

@login_required(login_url='login')
def viewAccount(request, pk = None):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    try:
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            cartItems = order.get_cart_items
        else:
            order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    except:
        cartItems = 0
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'cartItems':cartItems,'user':user}
    return render(request,'accounts/account.html',args)

@login_required(login_url='login')
def accountSettings(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    try:
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            cartItems = order.get_cart_items
        else:
            order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    except:
        cartItems = 0

    group = Group.objects.get(name = 'customer')

    try: 
        customer = request.user.customer
        form = CustomerForm(instance=customer)
    except:
        shopowner = request.user.shopowner
        form = ShopOwnerForm(instance=shopowner)

    form2 = UpdateProfileForm(instance=request.user)
    if request.method == 'POST':
        try:
            form = CustomerForm(request.POST, request.FILES, instance=customer)
        except:
            form = ShopOwnerForm(request.POST, request.FILES, instance=shopowner)
            
        form2 = UpdateProfileForm(request.POST, instance=request.user)
        if (form and form2).is_valid():
            form.save()
            form2.save()
            return redirect('/account')
    context = {'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'form':form,'cartItems':cartItems,'form2':form2}
    return render(request,'accounts/account_settings.html',context)

@login_required(login_url='login')
def change_password(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer

accounts/templates/accounts/categoryform.html
{% extends 'accounts/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card card-body">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="name" placeholder="Enter new category" maxlength="200" required="" id="id_name">
                    <input style="margin-top: 20px;" type="submit" class="btn btn-success">
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <p>Are you sure you want to delete "{{ item }}"?</p>
            <form action="{% url 'delete_order' item.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'home' %}">Cancel</a>
                <input type="submit" name="Confirm" class="btn btn-danger">
            </form>         
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/error.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card text-center">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Error!</h3> <br> <br>
				</div>
                    <h3 id="form-title">Someting went wrong. </h3> <br>
                    <p id="form-title">Please try again.</p><br>
                    <a class="btn btn-sm btn-info" href="{% url 'login' %}">Login</a>
                
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/accounts/navbar.html
{% load static %}
<style>
    .hello-msg{
        font-size:18px;
        color:#fff;
        margin-right: 20px;
    }
    #cart-icon{
      width: 25px;
      display: inline-block;
      margin-left: 15px;
      color: azure;
    }
    #cart-total{
      display: block;
      text-align: center;
      color: #fff;
      background-color: red;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      font-size: 14px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="{% static 'images/logo.png'%}" alt="" height="40px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if request.user.is_staff %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products' %}">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account' %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user-page' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shops' %}">Shops</a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% if not request.user.is_staff %}
    <div class="form-inline my-2 my-lg-0">
      <a href="{% url 'cart' %}"><img src="{% static 'images/cart.png' %}" alt="" id="cart-icon"></a>
      <p id="cart-total">{{cartItems}}</p>

    </div>
    {% endif %}
    <span class="hello-msg">Hello, {{request.user}}</span>
    <span ><a class="hello-msg" href="{% url 'logout' %}">Logout</a></span>
  </nav>

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
<style>
    .product-form{
        width: 170px;
        float: left;
        display: inline-block;
        margin-right: 20px;
    }
    .dropdown-menu ul li{
        list-style: none;
    }
    .dropdown{
        display: inline-block;
        margin-right: 20px;
    }
    #myInput {
        background-image: url("{% static '/images/searchicon.png' %}"); 
        background-position: 10px 12px; 
        background-repeat: no-repeat; 
        width: 100%;
        font-size: 16px;
        padding: 12px 20px 12px 40px;
        border: 1px solid #ddd; 
        margin-bottom: 12px;
        margin-top: -10px;
    }
</style>
<script>
    function tagFunction() {
      var input, filter, ul, li, a, i, txtValue;
      input = document.getElementById('tagInput');
      filter = input.value.toUpperCase();
      ul = document.getElementById("id_tags");
      li = ul.getElementsByTagName('li');
    
      for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("label")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          li[i].style.display = "";
        } else {
          li[i].style.display = "none";
        }
      }
    }
    function categoryFunction() {
      var input, filter, ul, li, a, i, txtValue;
      input = document.getElementById('categoryInput');
      filter = input.value.toUpperCase();
      ul = document.getElementById("id_category");
      li = ul.getElementsByTagName('li');
    
      for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("label")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          li[i].style.display = "";
        } else {
          li[i].style.display = "none";
        }
      }
    }
    function searchFunction() {
      var input, filter, ul, li, a, i, txtValue;
      input = document.getElementById('searchInput');
      filter = input.value.toUpperCase();
      ul = document.getElementById("myTable");
      li = ul.getElementsByTagName('tr');
    
      for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("td")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          li[i].style.display = "";
        } else {
          li[i].style.display = "none";
        }
      }
    }
    </script>
{%endblock%}
{% block content %}

    <br>

    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <h5>Products</h5>
            </div>
            <div class="card card-body">
                <form action="" method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <input type="hidden" name="shopowner" value="{{request.user.shopowner.id}}">
                    <p class="product-form">
                        <label for="id_name"></label>
                        {{ form.name|add_class:'form-control' }}
                    </p>
                    <p class="product-form">
                        <label for="id_img"></label>
                        {{ form.img|add_class:'form-control' }}
                    </p>
                    <p class="product-form">
                        <label for="id_price"></label>
                        {{ form.price|add_class:'form-control' }}
                    </p>
                    <p class="product-form">
                        <label for="id_stock">In Stock : </label>
                        {{ form.stock|add_class:'form-control' }}
                    </p>
                        <div class="dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Select Category
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <input class="form-control" type="text" id="categoryInput" onkeyup="categoryFunction()" placeholder="Search tags">
                                {{form.category}}
                            </div>
                          </div>
                    <p class="product-form">
                        <textarea name="description" cols="40" rows="10" placeholder="Description" class="form-control" required="" id="id_description" style="margin-top: 0px; margin-bottom: 0px; height: 73px;"></textarea>
                    </p>
                        <div class="dropdown">
                            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Select Tags
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <input class="form-control" type="text" id="tagInput" onkeyup="tagFunction()" placeholder="Search tags">
                                {{form.tags}}
                            </div>
                          </div>
                    <input class="btn btn-warning" type="submit" name='Add'>
                </form>
            </div>
            <div class="card card-body">
                <div class="buttons">
                    <a href="{% url 'tag' %}" style="width: 200px;" class="btn btn-outline-info">Create Tag</a>
                    <a href="{% url 'category' %}" style="width: 200px;" class="btn btn-outline-info">Create Catgory</a>
                    <a href="{% url 'flash' %}" style="width: 200px;" class="btn btn-outline-success">Flash Discount</a>
                    <form method="GET">
                      {% csrf_token %}
                      <input type="hidden" name="id" value="0">
                      <input type="submit" class="btn btn-outline-danger" name="flash_discount" value="Remove flash discount">
                  </form></div>
            </div>
            <div class="card card-body">
                <input id="myInput" class="form-control" onkeyup="searchFunction()" type="text" placeholder="Search..">
                <br><br>
                <table class="table table-sm paginated">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Product</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Stock</th>
                            <th>Remove <br> discount</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                    {% for i in products %}
                        <tr>
                            <td><img src="{{ i.img.url }}" alt="Product Img" style="height: 50px;"></td>
                            <td>{{ i.name }}</td>
                            <td>{{ i.description }}</td>
                            <td>{{ i.price|floatformat:2 }}</td>
                            <td>{{ i.stock }}   <a href="{% url 'update_stock' i.id %}" class="btn btn-outline-success">Add</a>
                            </td>
                            <td><form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{i.id}}">
                                <input type="submit" class="btn btn-outline-danger" name="discount_amount" value="{{i.discount_amount|floatformat:2}}">
                            </form></td>
                            <td><a class="btn btn-sm btn-info" href="{% url 'product_setting' i.id %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger" href="#">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/tagform.html
{% extends 'accounts/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card card-body">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="name" placeholder="Enter new tag" maxlength="200" required="" id="id_name">
                    <input style="margin-top: 20px;" type="submit" class="btn btn-success">
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}