accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('register/',views.registerPage,name="register"),
    path('shopregister/',views.shopOwnerRegisterPage,name="shopregister"),
    path('token/',views.token_send,name="token_send"),
    path('success/',views.success,name="success"),
    path('verify/<auth_token>',views.verify,name="verify"),
    path('error/',views.error_page,name='error'),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('user/dashboard/',views.userPage,name='user-page'),
    path('account/',views.viewAccount,name='account'),
    path('account/edit/',views.accountSettings,name='edit_account'),
    path('change-password/',views.change_password,name = 'change_password'),
    path('', views.home,name='home'),
    path('products/', views.products,name='products'),
    path('flash_sell/', views.flashSell,name='flash'),
    path('products/setting/<str:pk>/', views.productSetting, name='product_setting'),
    path('customer/<str:pk>/', views.customers,name='customer'),
    path('update_order/<str:pk>/',views.updateOrder,name='update_order'),
    path('update_stock/<str:pk>/',views.updateStock,name='update_stock'),
    path('delete_order/<str:pk>/',views.deleteOrder,name='delete_order'),
    path('mail/',views.mail_letter,name='mail'),
    path('create/tag/',views.createTag,name='tag'),
    path('create/category/',views.createCategory,name='category'),
    path('reset-password/', PasswordResetView.as_view(
        template_name= 'accounts/reset_password.html',
        success_url=reverse_lazy('password_reset_done'),
        email_template_name= 'accounts/reset_password_email.html'
    ), name='reset_password'),

    path('reset-password/done/',PasswordResetDoneView.as_view(
        template_name= 'accounts/reset_password_done.html'
    ),name= 'password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(
        template_name= 'accounts/reset_password_confirm.html',
         success_url=reverse_lazy('password_reset_complete'),
    ),name= 'password_reset_confirm' ),
    path('reset-password/complete/',PasswordResetCompleteView.as_view(
        template_name= 'accounts/reset_password_complete.html'
    ),name ='password_reset_complete')
]

ecommerce_web/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('store/',views.store,name="store"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('shops/',views.shops,name="shops"),
    path('view_shop/<str:pk>/',views.view_shops,name="view_shop"),
    path('view/<str:pk>/',views.productView,name="view"),
    path('delete_review/<str:pk>/',views.deleteReview,name="delete_review"),
    path('update_item/',views.updateItem, name="update_item"),
    path('process_order/',views.processOrder, name="process_order"),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('ecommerce_web.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce_web/models.py
from django.db import models
from accounts.models import *

# Create your models here.
class OrderItem(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered','Delivered')
    )
    customer = models.ForeignKey(Customer, null=True, on_delete= models.SET_NULL)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    shop = models.ForeignKey(ShopOwner, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    status = models.CharField(default="Pending",max_length=200,blank=True, null=True,choices=STATUS)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.zipcode

class Subscriber(models.Model):
    email = models.EmailField(null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class MailMessage(models.Model):
    title = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)

    def __str__(self):
        return self.title
    
class Review(models.Model):
    user = models.ForeignKey(Customer, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

accounts/forms.py
from django.forms import ModelForm, fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms
from .models import *
from ecommerce_web.models import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields ='__all__'
        exclude = ['user']

class ShopOwnerForm(ModelForm):
    class Meta:
        model = ShopOwner
        fields ='__all__'
        exclude = ['user']

class OrderForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

class UpdateOrderForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'
        exclude = ['customer','shop']

class ProductForm(ModelForm):
    name = forms.CharField(label='Product Name',widget=forms.TextInput(attrs={'placeholder': 'Product Name'}))
    price = forms.FloatField(label='Price',widget=forms.TextInput(attrs={'placeholder': 'Price'}))
    description = forms.CharField(max_length=50,label='Description',widget=forms.Textarea(attrs={'placeholder': 'Max 50 words'}))
    tags = forms.ModelMultipleChoiceField(
            queryset=Tag.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    category = forms.ModelMultipleChoiceField(
            queryset=Category.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    
    class Meta:
        model = Product
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UpdateProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields =['email','first_name','last_name','password']
    
class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

ecommerce_web/forms.py
from django import forms
from .models import *

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields =['email',]
    
class MailMessageForm(forms.ModelForm):
    class Meta:
        model = MailMessage
        fields ='__all__'
    
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

ecommerce_web/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from django.http import JsonResponse
from accounts.models import *
from .filters import ProductFilter
import json
import datetime
from django.utils import timezone
from datetime import timedelta
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users
from .forms import SubscribeForm,ReviewForm

# Create your views here.
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def store(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Subscription Successful')
            return redirect('/store')
    else:
        form = SubscribeForm()

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
        cartItems = order['get_cart_items']
    products = Product.objects.all().order_by('-discount_amount','-discount','-stock','-date_created')
    date = timezone.now().date() - timedelta(days=7)
    product_week = Product.objects.filter(date_created__gt=(datetime.datetime.now()- timedelta(days=7))).order_by('-date_created')
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    total_products = products.count()
    productFilter = ProductFilter(request.GET,queryset=products)
    top_reviewed = Product.objects.all().order_by('-rate')
    products = productFilter.qs
    context = {
    'total_products':total_products,
    'top_reviewed':top_reviewed,
    'product_week':product_week,
    'customers':customers,
    'shops':shops,
    'total_subscriber':total_subscriber,
    'form':form,
    'products':products,
    'cartItems':cartItems,
    'productFilter':productFilter
    }
    return render(request, 'store/store.html',context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def cart(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    context = {'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'items':items,'cartItems':cartItems,'order':order}
    return render(request, 'store/cart.html',context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def checkout(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    context = {'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'items':items,'order':order,'cartItems':cartItems}
    return render(request, 'store/checkout.html',context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productID']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    shopowner = product.shopowner
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(customer=customer, order=order, shop=shopowner, product=product, status='Pending')

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    elif action == 'delete':
        orderItem.quantity = 0

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True
            order.save()

        if order.shipping == True:
            ShippingAddress.objects.create(
                customer = customer,
                order = order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode'],
            )

    else:
        print('User is not logged in...')
    return JsonResponse('Payment complete!', safe=False)

def productView(request,pk):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    product = Product.objects.get(id = pk)
    demo_price = product.price + product.discount_amount

    review = product.review_set.all().order_by('-created_at')
    total_review = review.count()
    total_rate = 0
    for i in review:
        total_rate += i.rate
    try:
        avg_rating = total_rate/total_review
        product.rate = avg_rating
        product.save()
    except:
        avg_rating = 0
        product.rate = avg_rating
        product.save()
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        form.save()
        messages.success(request, 'Review Added')
        return redirect(reverse('view', kwargs={'pk':pk}))
    
    else:
        form = ReviewForm()

    stock = product.stock
    context = {'demo_price':demo_price,'stock':stock,'avg_rating':avg_rating,'review':review,'total_review':total_review,
    'form':form,'product':product,'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'cartItems':cartItems}
    return render(request, "store/view.html",context)

@login_required(login_url='login')
def deleteReview(request, pk):
    review = Review.objects.get(id=pk)
    if request.method == "POST":
        review.delete()
        return redirect('/')

    context = {'item':review}
    return render(request,'store/delete.html',context)

@login_required(login_url='login')
def shops(request):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    shopowner = ShopOwner.objects.all()

    context = {'shopowner':shopowner,'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'cartItems':cartItems}
    return render(request,'store/shops.html',context)

@login_required(login_url='login')
def view_shops(request,pk):
    shops = ShopOwner.objects.all().count()
    customers = Customer.objects.all().count()
    subscribers = Subscriber.objects.all()
    total_subscriber = subscribers.count()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        order = {'get_cart_total':0, 'get_cart_items':0,'shipping':False}
    shop = ShopOwner.objects.get(id=pk)
    products = Product.objects.filter(shopowner=shop)
    date = timezone.now().date() - timedelta(days=7)
    product_week = products.filter(date_created__gt=(datetime.datetime.now()- timedelta(days=7))).order_by('-date_created')
    top_reviewed = products.order_by('-rate')
    productFilter = ProductFilter(request.GET,queryset=products)
    products = productFilter.qs
    
    context = {'top_reviewed':top_reviewed,'product_week':product_week,'productFilter':productFilter,'products':products,'shop':shop,'customers':customers,'shops':shops,'total_subscriber':total_subscriber,'cartItems':cartItems}
    return render(request,'store/view_shop.html',context)

ecommerce_web/templates/store/delete.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <p>Are you sure you want to delete "{{ item }}"?</p>
            <form action="{% url 'delete_review' item.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'store' %}">Cancel</a>
                <input type="submit" name="Confirm" class="btn btn-danger">
            </form>         
        </div>
    </div>
</div>

{% endblock %}

ecommerce_web/templates/store/view.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block head %}
    
<style>
    
#footer{
    display: none;
  }
  #footer-user{
    display: block !important;
  }
  .rating{
    display: inline-flex;
    transform: rotateY(180deg);
    margin-top: -15px;
    
  }
  .rating input{
    display: none;
  }
  .rating label{
    display: block;
    cursor: pointer;
    width: 30px;
  }
  .rating label::before{
    content: '\f005';
    font-family: fontAwesome;
    position: relative;
    display: block;
    font-size: 30px;
    color: #101010;
  }
  .rating label::after{
    content: '\f005';
    font-family: fontAwesome;
    position: absolute;
    display: block;
    font-size: 30px;
    color: #ffc107;
    top:0;
    opacity: 0;
    transition: .5s;
    text-shadow: 0 2px 5px rgba(0, 0, 0, .5);
  }
  .rating label:hover::after,
  .rating label:hover ~ label::after,
  .rating input:checked ~ label::after{
    opacity: 1;
  }
  .view{
    margin-top: 20px;
  }
  .view_left{
    height: 630px;
  }
  .view_left img{
    display: block;
    margin: auto;
    max-width: 510px;
    max-height: 480px;
  }
  .view_left_down{
    margin-top: 20px;
  }
  .view_down{
    margin-top: 20px;
  }
  .collapsible {
    background-color: #dfdfdf;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 25px;
    text-align: center;
  }
#id_tags{
  height: 200px !important;
  overflow: auto;
}
  .active, .collapsible:hover {
    background-color: #dfdfdf;
  }

  .content {
    margin-top: 10px;
    padding: 0 18px;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
    background-color: #fff;
  }
  button:focus {
    outline: none !important;
}
.view_left img{
  transition: transform .2s; /* Animation */
}
.view_left img:hover {
  transform: scale(1.5);
  z-index: 99999; /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
.checked {
  color: #ffc107;
}
</style>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row view">
    <div class="col-md-6">
      <div class="card card-body view_left">
        <a href="{% url 'store' %}" class="btn btn-outline-info btn-md" style="width: 40%;">&#x2190; Continue Shopping</a>
        <img src="{{product.img.url}}" >
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-body">
            <h3>{{product.name}}</h3>
            <h5>{{product.description}}</h5>
            {% if product.discount > 0 %}
            <h5>Discount: {{product.discount}}%</h5>
            {% endif %}
            <h5>Price: {% if product.discount_amount > 0 %}
              <del>${{demo_price|floatformat:2}}</del>
              {% endif %}
               ${{product.price|floatformat:2}}</h5>
            <h5>Rating:	{{avg_rating|floatformat:1}}&#9733;</h5>
            {% if stock <= 0 %}
            <h5>Available: <p style="color: red; display: inline-block;">Out of stock</p></h5>
            <button class="btn btn-outline-danger btn-disabled">Add to Cart</button>
            {% else %}
            <h5>Available: <p style="color: green; display: inline-block;">In stock</p></h5>
            <button data-product={{product.id}} data-action="add" class="btn btn-outline-success add-btn update-cart">Add to Cart</button>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="card card-body view_left_down">
            <form method="POST">
              {%csrf_token%}
              <input type="hidden" name="user" id="id_user" value="{{request.user.customer.id}}">
              <input type="hidden" name="product" id="id_product" value="{{product.id}}">
              <p>Write your comment:</p>
              <textarea name="comment" class="form-control" placeholder="Write your comment within 250 letters......" cols="30" rows="4" maxlength="250" required="" id="id_comment"></textarea>
              <p>Select rating:</p>
              <div class="rating">
                <input type="radio" id="star1" name="rate" value="5"><label for="star1"></label>
                <input type="radio" id="star2" name="rate" value="4"><label for="star2"></label>
                <input type="radio" id="star3" name="rate" value="3"><label for="star3"></label>
                <input type="radio" id="star4" name="rate" value="2"><label for="star4"></label>
                <input type="radio" id="star5" name="rate" value="1"><label for="star5"></label>
              </div><br>
              <input type="submit" class="btn btn-success">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card card-body view_down">
        <button type="button" class="collapsible">{{total_review}} REVIEWS</button>
        <div class="content">
          {% for i in review %}
          <p>Reviewed by: <strong>{{i.user}} </strong>at {{i.created_at}}</p>
          <p>{{i.comment}}</p>
            <p class="star_review">
              {% if i.rate == 1 %}
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              {% elif i.rate == 2 %}
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              {% elif i.rate == 3 %}
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              {% elif i.rate == 4 %}
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              {% elif i.rate == 5 %}
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              {% endif %}
              </p>
              {% if request.user.customer == i.user %}
                <a href="{% url 'delete_review' i.id %}" class="btn btn-sm btn-outline-danger">Delete</a>
              {% endif %}
               <hr>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var coll = document.getElementsByClassName("collapsible");
  var i;
  
  for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var content = this.nextElementSibling;
      if (content.style.maxHeight){
        content.style.maxHeight = null;
      } else {
        content.style.maxHeight = content.scrollHeight + "px";
      } 
    });
  }
  </script>
{% endblock %}

ecommerce_web/templates/store/view_shop.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block content %}
<style>
#footer{
  display: none;
}
#footer-user{
  display: block !important;
}
.box-element{
    background-color: #fff;
    border-radius: 4px;
    padding: 10px;
}
.thumbnail{
    display: block;
    margin: auto;
    height: 200px;
    max-width: 300px;
    background-color: #fff;
}
.heading{
  display: inline-block;
  text-align: center;
  border: 2px solid green;
  padding: 10px;
}

.filter-form{
    float: left;
    display: inline-block;
    margin-right: 20px;
}
.dropdown-menu ul li{
    list-style: none;
}
.dropdown{
    display: inline-block;
    margin-right: 20px;
}
#product_name{
  margin-top: 20px;
}
</style>
<div class="container-fluid">
        <div class="row" id="product_name">
          <div class="col-md-2">
            <form action="" method="get">
              <p><input type="text" placeholder="Search product name..." id="searchInput" style="float: left;" class="form-control" name="name" id="id_name"> <br>
              <p class="filter-form">Price range: <br><br> <input type="number" class="form-control" placeholder="From..." name="start_price" id="id_start_price">
                <br><input type="number" class="form-control" placeholder="To..." name="end_price" id="id_end_price"></p>
              <p class="filter-form">Date added product:<br><br><input type="date" class="form-control" placeholder="From..." name="start_date" id="id_start_date">
              <br> <input type="date" class="form-control" placeholder="To..." name="end_date" id="id_end_date"></p>
              <div class="dropdown filter-form">
                <button style="width: 100%;" class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Filter Category
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <input class="form-control" type="text" id="categoryInput" onkeyup="categoryFunction()" placeholder="Search tags">
                    {{ productFilter.form.category }}
                </div>
              </div>
              <div class="dropdown filter-form">
               <button style="width: 100%;" class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Filter Tags
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <input class="form-control" type="text" id="tagInput" onkeyup="tagFunction()" placeholder="Search tags">
                    {{ productFilter.form.tags }}
                </div>
              </div>
              <p class="filter-form"><br><button class="btn btn-md btn-info" type="submit">Filter</button></p>
            </form>
          </div>
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-12">
                <div class="card card-body ">
                  <h3 class="heading">{{shop.user.first_name}} {{shop.user.last_name}}</h3>
                </div>
              </div>
            </div>
            <div class="row">    
             {% for product in products %}
        <div class="col-lg-3" style="margin-top:20px;">
            <div style="background-color: #fff;">
            <img class="thumbnail" src="{{ product.img.url }}" alt="">
            <div class="box-element product">
            <h6><strong>{{ product.name }}</strong></h6><hr>
            {% if product.stock <= 0 %}
            <button class="btn btn-disabled btn-outline-danger">Out of Stock</button>
            {% else %}
            <button data-product={{product.id}} data-action="add" class="btn btn-outline-success add-btn update-cart">Add to Cart</button>
            {% endif %}
            <a href="{% url 'view' product.id %}" class="btn btn-outline-success">View</a>
            <h4 style="display: inline-block; float: right;"> ${{product.price|floatformat:0}}</h4>
            </div>
        </div>
        </div>
  {% endfor %}
</div>
</div>
<div class="col-md-2">
  <form method="get">
    <p><input class="form-control" type="text" id="liveInput" onkeyup="productFunction()" placeholder="Search product...."> <br>
  </form>
  <p>Product added in last 7 days: </p>
  <div class="product_week" style="height: 45px; overflow: auto;">
    {% for i in product_week %}
    <a href="{% url 'view' i.id %}" class="btn btn-outline-info" style="margin-top: 5px;">{{i.name}}</a>
    {% endfor %}
  </div><br>
  <p>Top Reviewed Product: </p>
  <div class="top_reviewed" style="height: 45px; overflow: auto;">
    {% for i in top_reviewed %}
    {% if i.rate >= 3 %}
    <a href="{% url 'view' i.id %}" class="btn btn-outline-info" style="margin-top: 5px;"><strong>{{i.name}}</strong>: {{i.rate|floatformat:1}}&#9733;</a>
    {% endif %}
    {% endfor %}
  </div>
</div>
</div>
</div>
{% endblock %}